# Use Node.js as the base image
FROM node:20.9.0

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json .

COPY . .

# Install dependencies
RUN npm run build

# Expose the port the app runs on
EXPOSE 3000

# Start the application in development mode
CMD ["npm", "run", "start"]
