# Use Node.js as the base image
FROM node:18-alpine

# Set the working directory
WORKDIR /app

# Copy package files first for caching purposes
COPY ./frontend/package*.json ./

# Install dependencies
RUN npm ci

# Copy the rest of the application code
COPY ./frontend .

# Build the application
RUN npm run build

# Ensure that the build output directory is created
RUN ls -la .next

# Expose the port the app runs on
EXPOSE 3000

# Start the application
CMD ["npm", "start"]
