version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    env_file:
      - ./backend/.env
    restart: always

  backend:
    build:
      context: .
      dockerfile: ./backend/dockerfile
    command: python manage.py runserver 0.0.0.0:8800
    #    command: uvicorn backend.asgi:application --host 0.0.0.0 --port 8800 --workers 4
    volumes:
      - ./backend:/app
    depends_on:
      - db
    env_file:
      - .env
    restart: always

  frontend:
    build:
      context: .
      dockerfile: ./frontend/dockerfile
      target: deployment
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - .env.local
    depends_on:
      - backend

  nginx:
    build:
      context: .
      dockerfile: ./nginx/dockerfile
      target: deployment

    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
    depends_on:
      - backend
      - frontend
      - db

volumes:
  postgres_data:
