services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    env_file:
      - .env
    restart: always
  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8800
    #    command: uvicorn backend.asgi:application --host 0.0.0.0 --port 8800 --workers 4
    volumes:
      - ./backend:/app
    ports:
      - "8800:8800"
    depends_on:
      - db
    env_file:
      - ../.env
    restart: always
  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - ../.env.local
    depends_on:
      - backend
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
      - db
volumes:
  postgres_data:
