# Dockerfile

FROM python:3.10-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Set working directory
WORKDIR /app

# Install dependencies
COPY requirements.txt /app/
RUN pip install -r requirements.txt

# Copy the project files
COPY . /app/

# Run migrations and start the server
CMD sh -c "python manage.py migrate && watchmedo auto-restart --directory=. --pattern=*.py --recursive python manage.py runserver 0.0.0.0:8800"
