# Generated by Django 5.0.2 on 2024-10-28 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodgeneration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodwallpaper',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
