# Generated by Django 5.0.2 on 2024-10-28 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodgeneration', '0002_alter_moodwallpaper_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodwallpaper',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='moodwallpapers/'),
        ),
    ]
