# Generated by Django 5.0.2 on 2024-10-29 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodgeneration', '0003_moodwallpaper_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moodwallpaper',
            name='image',
        ),
        migrations.AddField(
            model_name='moodwallpaper',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
