# Generated by Django 5.0.2 on 2024-11-13 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodgeneration', '0004_remove_moodwallpaper_image_moodwallpaper_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodwallpaper',
            name='answers',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moodwallpaper',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moodwallpaper',
            name='questions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
