# Generated by Django 3.2.25 on 2024-10-25 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_kinde_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kinde_client_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
