# Generated by Django 5.0.2 on 2024-10-31 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='subscription_type',
            field=models.CharField(choices=[('FREE', 'Free'), ('STANDARD', 'Standard'), ('PREMIUM', 'Premium')], default='FREE', max_length=10),
        ),
    ]
